# Generated by Django 3.2.9 on 2023-10-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231018_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='created_by',
        ),
    ]
