# Generated by Django 3.2.9 on 2023-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230813_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(related_name='people', through='app.CourseMember', to='app.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='coursereq',
            field=models.ManyToManyField(related_name='peoplereq', through='app.CourseRequest', to='app.Course'),
        ),
    ]
