# Generated by Django 3.2.9 on 2023-11-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_info',
            field=models.TextField(blank=True, default='KBZ Pay - 09699227094 (Mg Thura Lin Htut)', null=True),
        ),
        migrations.AlterField(
            model_name='coursemenugroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.course'),
        ),
    ]
