# Generated by Django 3.2.9 on 2023-11-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20231114_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='fcm_token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
