# Generated by Django 3.2.9 on 2023-11-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdevice_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='telegram',
            field=models.CharField(default='telegram', max_length=100),
        ),
    ]
