# Generated by Django 3.2.9 on 2023-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='Semester 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='telegram',
            field=models.CharField(default='synapsework', max_length=100),
        ),
    ]
